Add friends likes
mrSkobelev/java-filmorate pull request #5
Opened 2023-11-13 18:31 UTC by mrSkobelev

2023-11-16 05:30 UTC, avlin87 requested changes
Привет, Алексей,
Работа выглядит хорошо, смотри, пожалуйста, комментарии.

2023-11-16 05:30 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ExceptionHandler
Вынеси, пожалуйста, методы ExceptionHandler в отдельный класс:
```
@RestControllerAdvice
public class ErrorHandler {
```

пример метода:
```
	@ExceptionHandler
	@ResponseStatus(HttpStatus.NOT_FOUND)
	public ErrorResponse handleNotFoundException(final DataNotFoundException e) {
		log.info("404 {}", e.getMessage());
		return new ErrorResponse(e.getMessage());
	}
```
обрати, пожалуйста, внимание, что в этом примере есть логирование, что очень важно в случае ошибки.

2023-11-16 05:30 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @ExceptionHandler
Вынеси, пожалуйста, методы ExceptionHandler в отдельный класс:
```
@RestControllerAdvice
public class ErrorHandler {
```

пример метода:
```
	@ExceptionHandler
	@ResponseStatus(HttpStatus.NOT_FOUND)
	public ErrorResponse handleNotFoundException(final DataNotFoundException e) {
		log.info("404 {}", e.getMessage());
		return new ErrorResponse(e.getMessage());
	}
```
обрати, пожалуйста, внимание, что в этом примере есть логирование, что очень важно в случае ошибки.

2023-11-16 05:30 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
NotFoundException - это исключение уже существует в библиотеке Java
Переименуй, пожалуйста, в DataNotFoundException или что-то такое.

2023-11-16 05:30 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        } else {
Писать else нет необходимости. В случае если сработает if - то исполнение этого метода уже прекратиться.

2023-11-16 05:30 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        char[] descriptionChars = film.getDescription().toCharArray();
У String есть метод `.length()`.
Лучше использовать его чем преобразовывать к массиву символов.

2023-11-16 05:30 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (descriptionChars.length > 200) {
200 можно вынести в константы.

2023-11-16 05:30 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        LocalDate validationDate = LocalDate.of(1895, 12, 28);
LocalDate.of(1895, 12, 28); так же можно вынести в константы класса.

2023-11-16 05:30 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            String[] login = user.getLogin().trim().split(" ");
У String есть метод `.length()`.
Лучше использовать его чем преобразовывать к массиву символов.

2023-11-16 12:07 UTC, mrSkobelev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            String[] login = user.getLogin().trim().split(" ");
Добрый день! В этом месте я привожу не к массиву символов а к массиву строк. тут я проверяю количество слов))

2023-11-16 12:13 UTC, mrSkobelev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (descriptionChars.length > 200) {
Не проходит валидация гит если константы указывать верхним регистром. Оставил lowerCamelCase

2023-11-16 21:34 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (descriptionChars.length > 200) {
Может если еще указать переменную static, то тогда пройдет валидация.

2023-11-16 21:39 UTC, avlin87 requested changes
Добавил два комментария.

2023-11-16 21:39 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorResponse.java
> +public class ErrorResponse {
Я полагал, что это класс нужен для ErrorHandler.
Не могу найти где ты его используешь.

Удали, пожалуйста, если действительно не используешь его нигде,
или используй, где планировал, когда создавал.

2023-11-16 21:39 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorResponse.java
> +    String error;
Переменные класса лучше делать приватными для соблюдения принципов ООП (инкапсуляция).

2023-11-17 21:47 UTC, avlin87 approved these changes
Хорошо. Работу принимаю.

2023-11-29 22:37 UTC, merged